import eslint from '@eslint/js';
import tseslint from 'typescript-eslint';

export default [
  eslint.configs.recommended,
  ...tseslint.configs.recommended,
  {
    rules: {
      '@typescript-eslint/ban-ts-comment': 'off',
      '@typescript-eslint/no-explicit-any': 'warn',
      '@typescript-eslint/no-unused-vars': 'warn',
      '@typescript-eslint/no-this-alias': 'off',
      'array-callback-return': 'warn',
      'arrow-body-style': ['warn', 'as-needed'],
      curly: 'warn',
      'default-case': 'warn',
      'dot-notation': 'warn',
      eqeqeq: 'error',
      'func-names': ['warn', 'as-needed'],
      'no-await-in-loop': 'warn',
      'no-debugger': 'warn',
      'no-eq-null': 'error',
      'no-inline-comments': 'warn',
      'no-mixed-spaces-and-tabs': 'off',
      'no-plusplus': 'warn',
      'no-unreachable': 'warn',
      'no-use-before-define': 'error',
      'no-var': 'warn',
      'object-shorthand': 'warn',
      'prefer-const': 'warn',
      'prefer-exponentiation-operator': 'warn',
      'prefer-promise-reject-errors': 'warn',
      'prefer-rest-params': 'error',
      semi: ['warn', 'always'],
      'require-await': 'warn',
      'use-isnan': 'warn',
    },
    ignores: [
      'node_modules',
      'dist',
      'build',
      'coverage',
      '.turbo',
      '.eslintrc.js',
      '.d.ts',
    ],
  },
];
