'use strict';

module.exports = {
  root: true,
  extends: [
    'eslint:recommended',
    'plugin:@typescript-eslint/recommended',
    'plugin:react/recommended',
    'plugin:react-hooks/recommended',
    'plugin:jsx-a11y/recommended',
  ],
  parser: '@typescript-eslint/parser',
  plugins: ['@typescript-eslint', '@stylistic'],
  env: {
    node: true,
    browser: true,
    es2024: true,
    /** use "test or expect" without any lint err  */
    jest: true,
  },
  parserOptions: {
    ecmaVersion: 'latest',
    sourceType: 'module',
    ecmaFeatures: {
      jsx: true,
    },
  },
  rules: {
    '@stylistic/array-bracket-newline': [
      'error',
      { multiline: true, minItems: 4 },
    ],
    '@stylistic/arrow-parens': ['warn', 'as-needed'],
    '@stylistic/arrow-spacing': 'error',
    '@stylistic/block-spacing': 'error',
    '@stylistic/brace-style': 'error',
    '@stylistic/comma-dangle': ['warn', 'always-multiline'],
    '@stylistic/comma-spacing': 'error',
    '@stylistic/eol-last': 'warn',
    '@stylistic/function-call-argument-newline': ['error', 'consistent'],
    '@stylistic/function-paren-newline': ['error', 'consistent'],
    '@stylistic/indent': ['error', 2],
    '@stylistic/jsx-closing-bracket-location': 'error',
    '@stylistic/jsx-closing-tag-location': 'error',
    '@stylistic/jsx-curly-newline': ['warn', 'consistent'],
    '@stylistic/jsx-curly-spacing': 'error',
    '@stylistic/jsx-equals-spacing': 'error',
    '@stylistic/jsx-first-prop-new-line': ['warn', 'multiline-multiprop'],
    '@stylistic/jsx-indent': ['error', 2],
    '@stylistic/jsx-indent-props': ['error', 2],
    '@stylistic/jsx-one-expression-per-line': ['warn', { allow: 'literal' }],
    '@stylistic/jsx-props-no-multi-spaces': 'error',
    '@stylistic/jsx-quotes': ['warn', 'prefer-double'],
    '@stylistic/jsx-self-closing-comp': 'error',
    '@stylistic/jsx-wrap-multilines': [
      'warn',
      {
        arrow: 'parens-new-line',
        assignment: 'parens-new-line',
        condition: 'parens-new-line',
        declaration: 'parens-new-line',
        logical: 'parens-new-line',
        return: 'parens-new-line',
      },
    ],
    '@stylistic/key-spacing': 'error',
    '@stylistic/linebreak-style': 'warn',
    '@stylistic/lines-around-comment': 'warn',
    '@stylistic/no-extra-semi': 'error',
    '@stylistic/no-floating-decimal': 'error',
    '@stylistic/no-mixed-operators': 'error',
    '@stylistic/no-mixed-spaces-and-tabs': 'warn',
    '@stylistic/no-multi-spaces': 'error',
    '@stylistic/no-multiple-empty-lines': 'error',
    '@stylistic/no-trailing-spaces': 'warn',
    '@stylistic/object-curly-newline': ['error', { multiline: true }],
    '@stylistic/object-curly-spacing': ['error', 'always'],
    '@stylistic/object-property-newline': 'warn',
    '@stylistic/operator-linebreak': ['error', 'before'],
    '@stylistic/quotes': ['error', 'single'],
    '@stylistic/semi-spacing': 'warn',
    '@stylistic/spaced-comment': 'warn',
    '@stylistic/switch-colon-spacing': 'warn',
    '@stylistic/template-curly-spacing': 'error',
    '@stylistic/type-annotation-spacing': 'warn',
    '@stylistic/type-generic-spacing': 'error',
    '@stylistic/type-named-tuple-spacing': 'error',
    '@stylistic/wrap-regex': 'error',
    '@typescript-eslint/no-unused-vars': 'warn',
    '@typescript-eslint/no-this-alias': 'off',
    '@typescript-eslint/ban-ts-comment': 'warn',
    'array-callback-return': 'warn',
    'arrow-body-style': ['warn', 'as-needed'],
    curly: 'warn',
    'default-case': 'warn',
    'default-param-last': 'warn',
    'dot-notation': 'error',
    eqeqeq: 'error',
    'func-names': ['warn', 'as-needed'],
    'jsx-a11y/anchor-ambiguous-text': 'error',
    'jsx-a11y/control-has-associated-label': 'error',
    'no-await-in-loop': 'warn',
    'no-debugger': 'warn',
    'no-eq-null': 'error',
    'no-inline-comments': 'warn',
    'no-plusplus': 'warn',
    'no-unreachable': 'warn',
    'no-use-before-define': 'error',
    'no-var': 'warn',
    'object-shorthand': 'error',
    'prefer-const': 'error',
    'prefer-exponentiation-operator': 'warn',
    'prefer-promise-reject-errors': 'warn',
    'prefer-rest-params': 'error',
    'react/react-in-jsx-scope': 'off',
    'react/jsx-uses-vars': 'error',
    'react/jsx-filename-extension': [
      'warn',
      {
        extensions: ['.tsx', '.jsx'],
      },
    ],
    semi: ['error', 'always'],
    'require-await': 'error',
    'use-isnan': 'warn',
  },
  settings: {
    react: {
      version: 'detect',
    },
  },
  /**
   * .eslintignore config, unlike .gitignore,
   *  "/" is used instead of "\"
   */
  ignorePatterns: [
    'node_modules',
    'dist',
    'build',
    'coverage',
    '.next',
    '.turbo',
    '.eslintrc.js',
    '*.d.ts',
  ],
};
