name: Build Docs

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.10.0'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install yarn globally
        run: npm i -g yarn

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      
      - name: Build Docs
        run: yarn docs:build