name: Publish eslint-flat-config

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: '24.14.0'
          registry-url: 'https://registry.npmjs.org'
      - run: sh scripts/pack.sh
      - run: npm publish
        working-directory: packages/eslint-flat-config
